### ISSUE TITLE
customLog

### ISSUE THREAD

**Issue by foxpjustin** [joshmanders/node-by-example#13]
console.log(); is great for testing, but when you have a function implemented via a launchDaemon and you want a PERMANENT record this will help.

```javascript
var fs = require('fs');
var now = new Date();
var year = now.getFullYear();
var thisMonth = zeroFill (now.getMonth() + 1);
var date = zeroFill (now.getDate());
var hour = zeroFill (now.getHours());
var minutes = zeroFill (now.getMinutes());
var seconds = zeroFill (now.getSeconds());
function zeroFill (i) {
	return (i < 10 ? '0' : '') + i;
}
function customLog (logMessage){
	now = new Date();
	var logfile = '/Library/Logs/AutomationLog/' + year + thisMonth + date + '_automation.txt'
	var logtime = hour + ':' + minutes + ':' + seconds;
	fs.stat (logfile, function (err,stats){
		if (!err && stats.isFile()){
			fs.appendFileSync (logfile, logtime + ' ' + logMessage + '\n');
		} else {
			fs.writeFile(logfile, logtime + ' ' + logMessage + '\n');
		};
	});
}
customLog('I done real good.');
```

**Comment by joshmanders** [comment]
Not exactly sure what you're asking or proposing with this issue. Care to elaborate?

**Comment by foxpjustin** [comment]
Perhaps I clicked on the wrong thing. I got here from the call for submissions. Not an Issue. A submission to be used as an intermediate example. Sorry for the breach in etiquette.

**Comment by joshmanders** [comment]
Ah I see. Please resubmit as a pull request and make sure that it adheres to the guidelines available at https://github.com/joshmanders/node-by-example/blob/master/CONTRIBUTING.md#-example-style-guide

Such as using template literals over string concatenation, `const` or `let` over `var`.

**Comment by foxpjustin** [comment]
I don't think that template literals are going to work in this case, this is part of a script that I am using to automate on a mac. When I try to use template literals in the terminal I am told that the back tick (`) is an illegal character. Maybe this isn't the place for my example.

**Comment by joshmanders** [comment]
What version of Node are you using?

**Comment by foxpjustin** [comment]
Thank you. I'm a graphics guy who started scripting out of necessity. I'm a little thick sometimes.

**Comment by joshmanders** [comment]
No worries. You're a prime example of what this project is for. :)

**Comment by foxpjustin** [comment]
I hope I did that right.
