### ISSUE TITLE
Use of 'use strict'; in all files.

### ISSUE THREAD

**Issue by doyouevennodebro** [joshmanders/node-by-example#6]
Comments closing issues #3 and #5, there was discussion of the need for 'use strict'; with ES6/ES2015, as well as the global usage in this community of ES6/ES2015 as a standard.

As such, all code, regardless of whether or not it invokes ES6/ES2015 specific syntax, should start with:

    'use strict';

Thanks.
-doyouevennodebro

**Comment by joshmanders** [comment]
Good suggestion, adding it now.
